name: My First Workflow

on: 
    push:
    workflow_dispatch:

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Welcome Message
              run: echo "Hi, My first GitHub Actions Job"

            - name: List Files
              run: ls -lsrt
            
            - name: Read Files
              run: cat README.md
