name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "Hi, My first GitHub Actions Job"

            - name: List Files
              run: ls -lsrt
            
            - name: Read Files
              run: cat README.md